version: "3.0.0-alpha.87"
image: ghcr.io/elias1731/ha-matter-addon
slug: hamh
name: 🌀 heyFordy's Matter-Hub
description: Custom HAMH
url: https://github.com/elias1731/ha-matter-addon
panel_icon: mdi:hub
panel_title: 🌀• MatterHub
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
