name: Mailcow Add-on
version: 1.0
slug: mailcow-addon
description: Integration von Mailcow in Home Assistant.
url: https://github.com/elias1731/fordys-ha-repo
webui: http://[HOST]:[PORT:8080]
arch:
  - arm64
  - amd64
init: false
map:
  - addon_config:rw
  - share:rw
  - media:rw
  - ssl
video: true
ports:
  8080/tcp: 8080
  8443/tcp: 8443
ports_description:
  8080/tcp: HTTP
  8443/tcp: TLS port