# Basis ist das offizielle Muse Docker-Image
FROM ghcr.io/museofficial/muse:latest

# Arbeitsverzeichnis
WORKDIR /app

# Add-on Startbefehl (optional, falls Anpassungen notwendig sind)
CMD ["node", "index.js"]
