version: "3.8"
services:
  muse:
    image: ghcr.io/museofficial/muse:latest
    restart: always
    volumes:
      - /data/muse:/data
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
