name: "RWFC Discord Status"
version: "0.1.0"
slug: "rwfc-discord-status"
description: "Updates a Discord Bot's status based on a Home Assistant sensor."
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share
options:
  discord_bot_token: ""
  sensor_entity_id: "sensor.default_sensor"
  update_interval: 60 # in Sekunden
  activity_type: "playing" # playing, watching, listening, streaming, competing
  status_template: "{state}" # Vorlage für den Status, z.B. "Temperatur: {state}°C" oder "Status: {state}"
schema:
  discord_bot_token: "password" # Wichtig: Als Passwort behandeln
  sensor_entity_id: "str"
  update_interval: "int(30,)" # Mindestens 30 Sekunden
  activity_type: "list(playing|watching|listening|streaming|competing)"
  status_template: "str"
image: "ghcr.io/elias1731/fordys-ha-repo/" # Passe dies an dein GitHub Repo an
